### ISSUE TITLE
NoYTNo is not working on a 6s @ iOS 13.3

### ISSUE THREAD

**Issue by leandroprz** [MeBlackHat/meblackhat.github.io#1]
I got these two popups since I've installed the tweak NoYTNo: https://imgur.com/a/A1LOjQG

I'm using a 6s with iOS 13.3.

**Comment by MeBlackHat** [comment]
I'm still working on an update. This tweak will be updated soon for updates follow me on reddit

**Comment by MeBlackHat** [comment]
> I got these two popups since I've installed the tweak NoYTNo: https://imgur.com/a/A1LOjQG
> 
> I'm using a 6s with iOS 13.3.

I'm still working on an update. This tweak will be updated soon for updates follow me on reddit
